name: module

on:
  push:
    branches:
      - v4
  pull_request:
    branches:
      - v4

jobs:
  build:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: ${{ github.event_name == 'pull_request' && fromJSON('["ubuntu-latest"]') || fromJSON('["ubuntu-latest", "windows-latest"]') }} # macos-latest
        node: [22]

    env:
      NUXT_GITHUB_TOKEN: ${{ secrets.NUXT_GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Prepare
        run: pnpm run dev:prepare

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

      - name: Test
        run: pnpm run test run

      - name: Build
        run: pnpm run build

      - name: Build Nuxt playground
        run: pnpm run dev:build

      - name: Build Vue playground
        run: pnpm run dev:vue:build

      - name: Publish
        # Only publish preview package on ubuntu during PRs
        if: matrix.os == 'ubuntu-latest'
        run: pnpx pkg-pr-new publish --compact --no-template --pnpm

  playground:
    needs: build

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./playgrounds/nuxt

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Store commit SHA
        run: |
          echo "COMMIT_SHA=$(echo ${{ github.event.pull_request.head.sha || github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install latest nuxt/ui
        run: pnpm install https://pkg.pr.new/@nuxt/ui@${{ env.COMMIT_SHA }} --lockfile-only

      - name: Install dependencies
        run: pnpm install --ignore-workspace

      - name: Prepare
        run: pnpm nuxt prepare

      - name: Typecheck
        run: pnpm run typecheck

  starter:
    needs: build

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: nuxt-ui-templates/starter

      - name: Store commit SHA
        run: |
          echo "COMMIT_SHA=$(echo ${{ github.event.pull_request.head.sha || github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install latest nuxt/ui
        run: pnpm install https://pkg.pr.new/@nuxt/ui@${{ env.COMMIT_SHA }} --lockfile-only

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

  starter-vue:
    needs: build

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: nuxt-ui-templates/starter-vue

      - name: Store commit SHA
        run: |
          echo "COMMIT_SHA=$(echo ${{ github.event.pull_request.head.sha || github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install latest nuxt/ui
        run: pnpm install https://pkg.pr.new/@nuxt/ui@${{ env.COMMIT_SHA }} --lockfile-only

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Typecheck
        run: pnpm run typecheck

  landing:
    needs: build

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: nuxt-ui-templates/landing

      - name: Store commit SHA
        run: |
          echo "COMMIT_SHA=$(echo ${{ github.event.pull_request.head.sha || github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install latest nuxt/ui
        run: pnpm install https://pkg.pr.new/@nuxt/ui@${{ env.COMMIT_SHA }} --lockfile-only

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

  docs:
    needs: build

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: nuxt-ui-templates/docs

      - name: Store commit SHA
        run: |
          echo "COMMIT_SHA=$(echo ${{ github.event.pull_request.head.sha || github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install latest nuxt/ui
        run: pnpm install https://pkg.pr.new/@nuxt/ui@${{ env.COMMIT_SHA }} --lockfile-only

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

  saas:
    needs: build

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: nuxt-ui-templates/saas

      - name: Store commit SHA
        run: |
          echo "COMMIT_SHA=$(echo ${{ github.event.pull_request.head.sha || github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install latest nuxt/ui
        run: pnpm install https://pkg.pr.new/@nuxt/ui@${{ env.COMMIT_SHA }} --lockfile-only

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

  dashboard:
    needs: build

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: nuxt-ui-templates/dashboard

      - name: Store commit SHA
        run: |
          echo "COMMIT_SHA=$(echo ${{ github.event.pull_request.head.sha || github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install latest nuxt/ui
        run: pnpm install https://pkg.pr.new/@nuxt/ui@${{ env.COMMIT_SHA }} --lockfile-only

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

  dashboard-vue:
    needs: build

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: nuxt-ui-templates/dashboard-vue

      - name: Store commit SHA
        run: |
          echo "COMMIT_SHA=$(echo ${{ github.event.pull_request.head.sha || github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install latest nuxt/ui
        run: pnpm install https://pkg.pr.new/@nuxt/ui@${{ env.COMMIT_SHA }} --lockfile-only

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Typecheck
        run: pnpm run typecheck

  chat:
    needs: build

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: nuxt-ui-templates/chat

      - name: Store commit SHA
        run: |
          echo "COMMIT_SHA=$(echo ${{ github.event.pull_request.head.sha || github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install latest nuxt/ui
        run: pnpm install https://pkg.pr.new/@nuxt/ui@${{ env.COMMIT_SHA }} --lockfile-only

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

  portfolio:
    needs: build

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: nuxt-ui-templates/portfolio

      - name: Store commit SHA
        run: |
          echo "COMMIT_SHA=$(echo ${{ github.event.pull_request.head.sha || github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install latest nuxt/ui
        run: pnpm install https://pkg.pr.new/@nuxt/ui@${{ env.COMMIT_SHA }} --lockfile-only

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

  changelog:
    needs: build

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: nuxt-ui-templates/changelog

      - name: Store commit SHA
        run: |
          echo "COMMIT_SHA=$(echo ${{ github.event.pull_request.head.sha || github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install latest nuxt/ui
        run: pnpm install https://pkg.pr.new/@nuxt/ui@${{ env.COMMIT_SHA }} --lockfile-only

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

  editor:
    needs: build

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: nuxt-ui-templates/editor

      - name: Store commit SHA
        run: |
          echo "COMMIT_SHA=$(echo ${{ github.event.pull_request.head.sha || github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install latest nuxt/ui
        run: pnpm install https://pkg.pr.new/@nuxt/ui@${{ env.COMMIT_SHA }} --lockfile-only

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build
