name: stale

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      issues: write

    steps:
      - uses: actions/stale@4c023f01d613e60293d8004f251a18bfb9bbd71d
        with:
          days-before-pr-stale: -1
          days-before-stale: 60
          days-before-close: 7
          any-of-labels: 'triage,question'
          stale-issue-label: 'stale'
          stale-issue-message: |
            Hi! ðŸ‘‹ This issue has been open for 60 days without activity and will be closed in 7 days. Please comment if it's still relevant.
          close-issue-label: 'closed-by-bot'
          close-issue-message: |
            Hi! ðŸ‘‹ This issue was automatically closed due to inactivity. If it's still relevant with the latest Nuxt UI version, feel free to reopen or create a new issue.
          operations-per-run: 300
